### PR TITLE
prim/ScopedLock: Fix makeScopedLock for pre-C++17 builds

### PR DESCRIPTION
**Pull request by leoetlino**
See https://github.com/open-ead/sead/pull/105#pullrequestreview-1064473605

@MonsterDruide1 let me know if this fixes makeScopedLock on Clang 3.9.

- - -
This change is [Reviewable](https://reviewable.io/reviews/open-ead/sead/106)

### CODE REVIEW

**Comment by MonsterDruide1** [comment]
No, still has the same issue as before:
```
/home/monsterdruide1/OdysseyDecompSead/OdysseyDecomp/lib/sead/modules/src/heap/seadHeapMgr.cpp:237:10: error: call to deleted constructor of 'sead::ScopedLock<sead::CriticalSection>'
    auto lock = makeScopedLock(sHeapTreeLockCS);
         ^      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/monsterdruide1/OdysseyDecompSead/OdysseyDecomp/lib/sead/include/prim/seadScopedLock.h:23:5: note: 'ScopedLock' has been explicitly marked deleted here
    ScopedLock(const ScopedLock& other) = delete;
    ^
    ```

**Comment by leoetlino** [comment]
Looks like this PR has fixed makeScopedLock at least, but not the usages.

You might need to do `auto lock{makeScopedLock(...)}`

**Comment by MonsterDruide1** [comment]
Nope, still not working:
```
/home/monsterdruide1/OdysseyDecompSead/OdysseyDecomp/lib/sead/modules/src/heap/seadHeapMgr.cpp:237:10: error: call to deleted constructor of 'sead::ScopedLock<sead::CriticalSection>'
    auto lock{makeScopedLock(sHeapTreeLockCS)};
         ^   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/monsterdruide1/OdysseyDecompSead/OdysseyDecomp/lib/sead/include/prim/seadScopedLock.h:23:5: note: 'ScopedLock' has been explicitly marked deleted here
    ScopedLock(const ScopedLock& other) = delete;
    ^
```

**Comment by leoetlino** [comment]
Ugh I guess you still need C++17 copy/move elision for this to work. I think we can make this work by adding a move constructor to ScopedLock...

**Comment by leoetlino** [comment]
@MonsterDruide1 can you try again?

**Comment by MonsterDruide1** [comment]
Now getting a different error:
```
/home/monsterdruide1/OdysseyDecompSead/OdysseyDecomp/lib/sead/include/prim/seadScopedLock.h:16:53: error: overload resolution selected deleted operator '='
    ScopedLock(ScopedLock&& other) noexcept { *this = other; }
                                              ~~~~~ ^ ~~~~~
```

**Comment by leoetlino** [comment]
Whoops, looks like I forgot to std::move the value... I'll fix this tonight

**Comment by leoetlino** [comment]
@MonsterDruide1 should be fixed now

**Comment by MonsterDruide1** [comment]
Sorry for the delay, but - yes, this works correctly now, and results in the same match!

**Pull request merged**
