### PR TITLE
math: Fix friend functions and add Vec3 negate

### PR DESCRIPTION
**Pull request by ThePixelGamer**
This change is [Reviewable](https://reviewable.io/reviews/open-ead/sead/91)

### CODE REVIEW

**Review by leoetlino — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/open-ead/sead/91)* status: all files reviewed, 1 unresolved discussion (waiting on @ThePixelGamer)

___
*[include/math/seadVector.h, line 148 at r1](https://reviewable.io/reviews/open-ead/sead/91#-MrIwSQ2363Z6etgcYub:-MrIwSQ2363Z6etgcYuc:b-qv4jns) ([raw file](https://github.com/open-ead/sead/blob/9b42350bc776594de9547fbab2a2fbfd2d72b182/include/math/seadVector.h#L148)):*
> ```objc
>     Vector4& operator+=(const Vector4& other);
> 
>     friend Vector4<T> operator+(const Vector4<T>& a, const Vector4<T>& b)
> ```

Why was `<T>` added here (and below)? That's a bit inconsistent. Does template argument deduction not work here?

**Comment by ThePixelGamer** [comment]
___
*[include/math/seadVector.h, line 148 at r1](https://reviewable.io/reviews/open-ead/sead/91#-MrIwSQ2363Z6etgcYub:-MrIySvF0_5b0ZJMLZSj:bqz991f) ([raw file](https://github.com/open-ead/sead/blob/9b42350bc776594de9547fbab2a2fbfd2d72b182/include/math/seadVector.h#L148)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

Why was `<T>` added here (and below)? That's a bit inconsistent. Does template argument deduction not work here?
</blockquote></details>

It should work, this is just a copy paste mistake

**Review by leoetlino — APPROVED** [review]
lgtm, just don't forget to fix the lint issues

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/open-ead/sead/91#-:-MrJ-_9G8YxuWRybqcaY:b5v8lpw)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ThePixelGamer)

**Review by leoetlino — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/open-ead/sead/91#-:-MrJ0NnXBaq0chXR4CS5:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ThePixelGamer)

**Pull request merged**
