### PR TITLE
gfx/PrimitiveRenderer: Cleanup, better headers

### PR DESCRIPTION
**Pull request by MonsterDruide1**
Some of these changes also originate from the SuperMarioOdysseyOnline repository, but have been cleaned and improved with more knowledge from the binary, along with all listed functions added.

- - -
This change is [Reviewable](https://reviewable.io/reviews/open-ead/sead/108)

### CODE REVIEW

**Comment by GRAnimated** [comment]
these originated from my fixed headers! thank you for PRing these i would never have gotten to it
but, this PR also removes the wii u implementation that was previously there (which I didn't need in odyssey), but i'm not sure if this project still wants those or not

**Comment by MonsterDruide1** [comment]
Do you mean the part of `QuadArg` and `CubeArg` that got "removed"? No, it was only moved up to the top of the file, into the right class, as they are a descendant of `PrimitiveDrawer` instead of `PrimitiveRenderer`.

**Comment by GRAnimated** [comment]
iirc from talking in the zelda decomp server, at some point between the Wii U and Switch, Nintendo substantially changed the primitive headers
abood's sead repo only has PrimitiveRenderer, which covers everything including those shape types
at some point, Nintendo renamed PrimitiveRenderer to PrimitiveDrawer, and created a new class called PrimitiveRenderer that calls the drawer
the current open-ead PrimitiveRenderer header is from abood's repo, which is the older version

**Comment by MonsterDruide1** [comment]
Oh, okay - I remember something about those two types, right. Well, it's up to @leoetlino whether those should stay, maybe included/excluded dynamically using `#ifdef`s?

**Review by leoetlino — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/open-ead/sead/108)* status: all files reviewed, 9 unresolved discussions (waiting on @MonsterDruide1)

___
*[`include/gfx/seadPrimitiveRenderer.h` line 26 at r1](https://reviewable.io/reviews/open-ead/sead/108#-N9YEeE03Twwo59jSEVH:-N9YEeE03Twwo59jSEVI:b-jtpesq) ([raw file](https://github.com/open-ead/sead/blob/cd9e753ad91405295a1a7afdea14b0afd4809258/include/gfx/seadPrimitiveRenderer.h#L26)):*
> ```objc
>     {
>     public:
>         inline QuadArg(Vector3f pos, Vector2f size, Color4f color = Color4f(255, 255, 255, 1),
> ```

This should use an initialiser list, i.e.

```cpp
QuadArg(...) : mCenter(pos), mSize(size), ... {}
```

(there's no need for `inline` here either)
___
*[`include/gfx/seadPrimitiveRenderer.h` line 36 at r1](https://reviewable.io/reviews/open-ead/sead/108#-N9YEhfV2A7l5RafuiB1:-N9YEhfV2A7l5RafuiB2:b-7xxz78) ([raw file](https://github.com/open-ead/sead/blob/cd9e753ad91405295a1a7afdea14b0afd4809258/include/gfx/seadPrimitiveRenderer.h#L36)):*
> ```objc
>         };
>         QuadArg()
>             : mCenter(Vector3f::zero), mSize(Vector2f::zero), mColor0(Color4f::cWhite),
> ```

This constructor can be replaced with `QuadArg() = default;` by initialising the members in-class (e.g. doing `Vector3f mCenter = Vector3f::zero;`)
___
*[`include/gfx/seadPrimitiveRenderer.h` line 41 at r1](https://reviewable.io/reviews/open-ead/sead/108#-N9YEtXf5S1KJELFvftH:-N9YEtXf5S1KJELFvftI:b98mwz0) ([raw file](https://github.com/open-ead/sead/blob/cd9e753ad91405295a1a7afdea14b0afd4809258/include/gfx/seadPrimitiveRenderer.h#L41)):*
> ```objc
>         }
> 
>         void setCornerAndSize(const Vector3f&, const Vector2f&);
> ```

parameter names
___
*[`include/gfx/seadPrimitiveRenderer.h` line 56 at r1](https://reviewable.io/reviews/open-ead/sead/108#-N9YEwJg5hIa7-oYDPTB:-N9YEwJg5hIa7-oYDPTC:b77y39k) ([raw file](https://github.com/open-ead/sead/blob/cd9e753ad91405295a1a7afdea14b0afd4809258/include/gfx/seadPrimitiveRenderer.h#L56)):*
> ```objc
>     {
>     public:
>         inline CubeArg(const BoundBox3f& box, const Color4f& color)
> ```

initialiser list
___
*[`include/gfx/seadPrimitiveRenderer.h` line 63 at r1](https://reviewable.io/reviews/open-ead/sead/108#-N9YEyev0XAwsDW3Rg8M:-N9YEyev0XAwsDW3Rg8N:b77y39k) ([raw file](https://github.com/open-ead/sead/blob/cd9e753ad91405295a1a7afdea14b0afd4809258/include/gfx/seadPrimitiveRenderer.h#L63)):*
> ```objc
>             mColor1 = color;
>         };
>         inline CubeArg(const Vector3f& pos, const Vector3f& size, const Color4f& color)
> ```

initialiser list
___
*[`include/gfx/seadPrimitiveRenderer.h` line 70 at r1](https://reviewable.io/reviews/open-ead/sead/108#-N9YEztR9lAZySt6COjG:-N9YEztR9lAZySt6COjH:b-7mc13x) ([raw file](https://github.com/open-ead/sead/blob/cd9e753ad91405295a1a7afdea14b0afd4809258/include/gfx/seadPrimitiveRenderer.h#L70)):*
> ```objc
>             mColor1 = color;
>         };
>         void setCornerAndSize(const Vector3f&, const Vector3f&);
> ```

names
___
*[`include/gfx/seadPrimitiveRenderer.h` line 80 at r1](https://reviewable.io/reviews/open-ead/sead/108#-N9YF0gx7JxoywsRdy55:-N9YF0gx7JxoywsRdy56:b-czkujm) ([raw file](https://github.com/open-ead/sead/blob/cd9e753ad91405295a1a7afdea14b0afd4809258/include/gfx/seadPrimitiveRenderer.h#L80)):*
> ```objc
>     };
> 
>     class UVArg
> ```

This should probably have a constructor, or be turned into a struct with public members.
___
*[`include/gfx/seadPrimitiveRenderer.h` line 87 at r1](https://reviewable.io/reviews/open-ead/sead/108#-N9YF7TK-ddwxDks08uc:-N9YF7TK-ddwxDks08ud:b4af60p) ([raw file](https://github.com/open-ead/sead/blob/cd9e753ad91405295a1a7afdea14b0afd4809258/include/gfx/seadPrimitiveRenderer.h#L87)):*
> ```objc
>     };
> 
>     PrimitiveDrawer(DrawContext* context);
> ```

explicit
___
*[`include/gfx/seadPrimitiveRenderer.h` line 89 at r1](https://reviewable.io/reviews/open-ead/sead/108#-N9YF84iC-C59MSySvvH:-N9YF84iC-C59MSySvvI:b5naozw) ([raw file](https://github.com/open-ead/sead/blob/cd9e753ad91405295a1a7afdea14b0afd4809258/include/gfx/seadPrimitiveRenderer.h#L89)):*
> ```objc
>     PrimitiveDrawer(DrawContext* context);
>     virtual ~PrimitiveDrawer();
>     void prepareMgrFromBinary(Heap*, const void*, u32);
> ```

Names. Same below

**Review by MonsterDruide1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/open-ead/sead/108)* status: all files reviewed, 9 unresolved discussions (waiting on @leoetlino)

___
*[`include/gfx/seadPrimitiveRenderer.h` line 26 at r1](https://reviewable.io/reviews/open-ead/sead/108#-N9YEeE03Twwo59jSEVH:-N9_yGakEp6Kx0gL8TeT:b-896fix) ([raw file](https://github.com/open-ead/sead/blob/cd9e753ad91405295a1a7afdea14b0afd4809258/include/gfx/seadPrimitiveRenderer.h#L26)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

This should use an initialiser list, i.e.

```cpp
QuadArg(...) : mCenter(pos), mSize(size), ... {}
```

(there's no need for `inline` here either)
</blockquote></details>

Done.
___
*[`include/gfx/seadPrimitiveRenderer.h` line 36 at r1](https://reviewable.io/reviews/open-ead/sead/108#-N9YEhfV2A7l5RafuiB1:-N9_yRYG6qDN0yTHImvK:b-896fix) ([raw file](https://github.com/open-ead/sead/blob/cd9e753ad91405295a1a7afdea14b0afd4809258/include/gfx/seadPrimitiveRenderer.h#L36)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

This constructor can be replaced with `QuadArg() = default;` by initialising the members in-class (e.g. doing `Vector3f mCenter = Vector3f::zero;`)
</blockquote></details>

Done.
___
*[`include/gfx/seadPrimitiveRenderer.h` line 41 at r1](https://reviewable.io/reviews/open-ead/sead/108#-N9YEtXf5S1KJELFvftH:-N9_za9v5NS_wgcCkEtZ:b-896fix) ([raw file](https://github.com/open-ead/sead/blob/cd9e753ad91405295a1a7afdea14b0afd4809258/include/gfx/seadPrimitiveRenderer.h#L41)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

parameter names
</blockquote></details>

Done.
___
*[`include/gfx/seadPrimitiveRenderer.h` line 56 at r1](https://reviewable.io/reviews/open-ead/sead/108#-N9YEwJg5hIa7-oYDPTB:-N9_ztRx8jeAXM11R3Ym:b-896fix) ([raw file](https://github.com/open-ead/sead/blob/cd9e753ad91405295a1a7afdea14b0afd4809258/include/gfx/seadPrimitiveRenderer.h#L56)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

initialiser list
</blockquote></details>

Done.
___
*[`include/gfx/seadPrimitiveRenderer.h` line 63 at r1](https://reviewable.io/reviews/open-ead/sead/108#-N9YEyev0XAwsDW3Rg8M:-N9_zszV1VeoCumCQKOX:b-896fix) ([raw file](https://github.com/open-ead/sead/blob/cd9e753ad91405295a1a7afdea14b0afd4809258/include/gfx/seadPrimitiveRenderer.h#L63)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

initialiser list
</blockquote></details>

Done.
___
*[`include/gfx/seadPrimitiveRenderer.h` line 70 at r1](https://reviewable.io/reviews/open-ead/sead/108#-N9YEztR9lAZySt6COjG:-N9_zu6xCa5JBTHyhs5n:b-896fix) ([raw file](https://github.com/open-ead/sead/blob/cd9e753ad91405295a1a7afdea14b0afd4809258/include/gfx/seadPrimitiveRenderer.h#L70)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

names
</blockquote></details>

Done.
___
*[`include/gfx/seadPrimitiveRenderer.h` line 80 at r1](https://reviewable.io/reviews/open-ead/sead/108#-N9YF0gx7JxoywsRdy55:-N9a-AuM2XLLNvkoCVAy:b-896fix) ([raw file](https://github.com/open-ead/sead/blob/cd9e753ad91405295a1a7afdea14b0afd4809258/include/gfx/seadPrimitiveRenderer.h#L80)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

This should probably have a constructor, or be turned into a struct with public members.
</blockquote></details>

Done.
___
*[`include/gfx/seadPrimitiveRenderer.h` line 87 at r1](https://reviewable.io/reviews/open-ead/sead/108#-N9YF7TK-ddwxDks08uc:-N9a-Dhb9A1VlX6QqTWF:b-896fix) ([raw file](https://github.com/open-ead/sead/blob/cd9e753ad91405295a1a7afdea14b0afd4809258/include/gfx/seadPrimitiveRenderer.h#L87)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

explicit
</blockquote></details>

Done.
___
*[`include/gfx/seadPrimitiveRenderer.h` line 89 at r1](https://reviewable.io/reviews/open-ead/sead/108#-N9YF84iC-C59MSySvvH:-N9a-mhqCWrrneiz9Psq:b-896fix) ([raw file](https://github.com/open-ead/sead/blob/cd9e753ad91405295a1a7afdea14b0afd4809258/include/gfx/seadPrimitiveRenderer.h#L89)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

Names. Same below
</blockquote></details>

Done.

**Review by leoetlino — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/open-ead/sead/108)* status: all files reviewed, 2 unresolved discussions (waiting on @MonsterDruide1)

___
*[`include/gfx/seadPrimitiveRenderer.h` line 28 at r2](https://reviewable.io/reviews/open-ead/sead/108#-N9aBEpUDlxMqp3KpbWd:-N9aBEpV8g6GgRiqi-NA:b-zj7bn) ([raw file](https://github.com/open-ead/sead/blob/24e603ebadf7139134a97baa2a130ef8ab1b404e/include/gfx/seadPrimitiveRenderer.h#L28)):*
> ```objc
>         QuadArg(Vector3f pos, Vector2f size, Color4f color = Color4f(255, 255, 255, 1),
>                 Color4f color2 = Color4f(255, 255, 255, 1), bool isHorizontal = false)
>             : mCenter(pos), mSize(size), mColor0(color), mColor1(color), mHorizontal(isHorizontal)
> ```

color2 is unused. Is that intended?

Also, are you sure the two default colour values are not Color4f::cWhite?
___
*[`include/gfx/seadPrimitiveRenderer.h` line 49 at r2](https://reviewable.io/reviews/open-ead/sead/108#-N9aBdQn2fD-vRB5kWOI:-N9aBdQn2fD-vRB5kWOJ:b-4ojvx0) ([raw file](https://github.com/open-ead/sead/blob/24e603ebadf7139134a97baa2a130ef8ab1b404e/include/gfx/seadPrimitiveRenderer.h#L49)):*
> ```objc
>     public:
>         CubeArg(const BoundBox3f& box, const Color4f& color)
>             : mCenter(box.getCenter()), mSize({box.getSizeX(), box.getSizeY(), box.getSizeZ()}),
> ```

No need for the inner set of braces for mSize.

**Review by MonsterDruide1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/open-ead/sead/108)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @leoetlino)

___
*[`include/gfx/seadPrimitiveRenderer.h` line 28 at r2](https://reviewable.io/reviews/open-ead/sead/108#-N9aBEpUDlxMqp3KpbWd:-NAPlPGp0jvKaOwmCzc6:b-x9y3en) ([raw file](https://github.com/open-ead/sead/blob/24e603ebadf7139134a97baa2a130ef8ab1b404e/include/gfx/seadPrimitiveRenderer.h#L28)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

color2 is unused. Is that intended?

Also, are you sure the two default colour values are not Color4f::cWhite?
</blockquote></details>

No, that should be used. I'm not sure about the `cWhite`, same for the default values below... the only usage that is not stubbed is in `sead::ScreenFiller::draw`, which seems to manually initialize the color parts with `1.0` each. Changed to `Color4f::cWhite` until we know differently from decompiling that function.
___
*[`include/gfx/seadPrimitiveRenderer.h` line 49 at r2](https://reviewable.io/reviews/open-ead/sead/108#-N9aBdQn2fD-vRB5kWOI:-NAPlrtDBI0vi9SbmBAk:b-896fix) ([raw file](https://github.com/open-ead/sead/blob/24e603ebadf7139134a97baa2a130ef8ab1b404e/include/gfx/seadPrimitiveRenderer.h#L49)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

No need for the inner set of braces for mSize.
</blockquote></details>

Done.

**Review by leoetlino — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/open-ead/sead/108)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @MonsterDruide1)

**Pull request merged**
