### PR TITLE
math: Pull latest changes

### LINKED ISSUE #86: Port the math additions and changes from the Wii U sead repo
- https://github.com/aboood40091/sead/commit/473723efaf515c7958a70dc7fe83f0f98fc8c909
- https://github.com/aboood40091/sead/commit/082f4c76330a3936b8e68fea1a1363be51e6155b
- https://github.com/aboood40091/sead/commit/537cf2eaf8f1f0cb48e8300a4db424ecf12435c5 (only the math changes)
- https://github.com/aboood40091/sead/commit/de6bf0a4a0e68052c70205fa0a06207351a98685
- https://github.com/aboood40091/sead/commit/8fce6b69eb9f1d1944a11a22ecef855431ec91b7 (only the math changes)

### PR DESCRIPTION
**Pull request by ThePixelGamer**
Closes #86

---
This change is [Reviewable](https://reviewable.io/reviews/open-ead/sead/87)

### CODE REVIEW

**Comment by aboood40091** [comment]
This misses changes to BoundBox in this comment:
https://github.com/aboood40091/sead/commit/8fce6b69eb9f1d1944a11a22ecef855431ec91b7

Also, Nintendo did not specialize MathCalcCommon::abs for float. It uses std::abs. (It is up to the compiler to place an fabs call or do something different)

**Comment by leoetlino** [comment]
std::abs and the current implementation of sead::absf (which was replaced with a specialisation in this PR) compile down to very different code: https://godbolt.org/z/dYv8bM1v1

Considering the second pattern is what we see in `sead::QuatCalcCommon<float>::slerpTo`, I think it's likely that MathCalcCommon's abs was specialised for float or that the generic implementation uses the ternary expression, not std::abs.

**Comment by aboood40091** [comment]
> std::abs and the current implementation of sead::absf (which was replaced with a specialisation in this PR) compile down to very different code: https://godbolt.org/z/dYv8bM1v1
> 
> Considering the second pattern is what we see in `sead::QuatCalcCommon<float>::slerpTo`, I think it's likely that MathCalcCommon's abs was specialised for float or that the generic implementation uses the ternary expression, not std::abs.

Hm... I needed to use `std::abs` for it to match on Wii U.

This could mean one of two things:
1. Nintendo changed the implementation for `sead::MathCalcCommon<T>::abs` (or specialized it for `float`) for newer versions specifically to the implementation in this pull request.
2. The specialized implementation for `float` in this pull request was actually the default implementaion all along and Nintendo specialized to for float on Wii U specifically to use `std::abs`.

To me, both sound equally likely (... or rather, equally unlikely because both cases are weird).

**Comment by ThePixelGamer** [comment]
In this case would it be better to have both definitions but combined with the preprocessor?

**Comment by ThePixelGamer** [comment]
Also this is something I'm unable to check but for classes like VectorCalcCommon wouldn't it be better to use the actual base structures for these functions as they don't really utilize any functions from actual class and we can just rely on implicit upcasting for the calls

**Pull request merged**
