### PR TITLE
gfx/TextWriter: Add all listed functions to header

### PR DESCRIPTION
**Pull request by MonsterDruide1**
This change is [Reviewable](https://reviewable.io/reviews/open-ead/sead/109)

### CODE REVIEW

**Review by leoetlino — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/open-ead/sead/109)* status: all files reviewed, 3 unresolved discussions (waiting on @MonsterDruide1)

___
*[`include/gfx/seadTextWriter.h` line 18 at r1](https://reviewable.io/reviews/open-ead/sead/109#-N9Y4_bK2SyuskiDNGCI:-N9Y4_bK2SyuskiDNGCJ:bbpap34) ([raw file](https://github.com/open-ead/sead/blob/3c680c59fd941543eb8ec2212ef605c58fa9934a/include/gfx/seadTextWriter.h#L18)):*
> ```objc
> {
> public:
>     TextWriter(DrawContext*);
> ```

explicit

Also please try to name the parameters when that's obvious/easy to do. (e.g. the DrawContext parameter should probably be called `context`)
___
*[`include/gfx/seadTextWriter.h` line 22 at r1](https://reviewable.io/reviews/open-ead/sead/109#-N9Y4oXs2DUTeW6H9LwR:-N9Y4oXt4QFz01gCeUMf:biwl2qb) ([raw file](https://github.com/open-ead/sead/blob/3c680c59fd941543eb8ec2212ef605c58fa9934a/include/gfx/seadTextWriter.h#L22)):*
> ```objc
>     virtual ~TextWriter();
> 
>     DebugFontMgrNvn* getDefaultFont();
> ```

Are you sure about the return type? Seems weird that "get default font" returns a font manager and not a font.

And if this does return a font manager, then this should probably be DebugFontMgr, not the Nvn subclass.
___
*[`include/gfx/seadTextWriter.h` line 25 at r1](https://reviewable.io/reviews/open-ead/sead/109#-N9Y4yxJ04PMuuSFZt_f:-N9Y4yxJ04PMuuSFZt_g:b-uttx8v) ([raw file](https://github.com/open-ead/sead/blob/3c680c59fd941543eb8ec2212ef605c58fa9934a/include/gfx/seadTextWriter.h#L25)):*
> ```objc
>     static void setDefaultFont(FontBase*);
>     static void setupGraphics(DrawContext*);
>     void getCursorFromTopLeft(Vector2f*);
> ```

Is this really not const qualified?

**Review by MonsterDruide1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/open-ead/sead/109)* status: all files reviewed, 3 unresolved discussions (waiting on @leoetlino)

___
*[`include/gfx/seadTextWriter.h` line 18 at r1](https://reviewable.io/reviews/open-ead/sead/109#-N9Y4_bK2SyuskiDNGCI:-N9_txGkCoMERHHxIWKw:b-896fix) ([raw file](https://github.com/open-ead/sead/blob/3c680c59fd941543eb8ec2212ef605c58fa9934a/include/gfx/seadTextWriter.h#L18)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

explicit

Also please try to name the parameters when that's obvious/easy to do. (e.g. the DrawContext parameter should probably be called `context`)
</blockquote></details>

Done.
___
*[`include/gfx/seadTextWriter.h` line 22 at r1](https://reviewable.io/reviews/open-ead/sead/109#-N9Y4oXs2DUTeW6H9LwR:-N9_uVEw4MlTkVwSPcXT:b-wls9mj) ([raw file](https://github.com/open-ead/sead/blob/3c680c59fd941543eb8ec2212ef605c58fa9934a/include/gfx/seadTextWriter.h#L22)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

Are you sure about the return type? Seems weird that "get default font" returns a font manager and not a font.

And if this does return a font manager, then this should probably be DebugFontMgr, not the Nvn subclass.
</blockquote></details>

Done. It returns a `DebugFontMgrNvn` by default, but can be overridden by `setDefaultFont`.
___
*[`include/gfx/seadTextWriter.h` line 25 at r1](https://reviewable.io/reviews/open-ead/sead/109#-N9Y4yxJ04PMuuSFZt_f:-N9_ua_mDKgLmEvyJUc2:b-896fix) ([raw file](https://github.com/open-ead/sead/blob/3c680c59fd941543eb8ec2212ef605c58fa9934a/include/gfx/seadTextWriter.h#L25)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

Is this really not const qualified?
</blockquote></details>

Done.

**Review by leoetlino — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/open-ead/sead/109)* status: all files reviewed, 5 unresolved discussions (waiting on @MonsterDruide1)

___
*[`include/gfx/seadTextWriter.h` line 24 at r2](https://reviewable.io/reviews/open-ead/sead/109#-N9aARGEBx5C8r5Es2JY:-N9aARGEBx5C8r5Es2JZ:bcm84rk) ([raw file](https://github.com/open-ead/sead/blob/caa76dba95c6e2806af6c895ef4454101c4a2cff/include/gfx/seadTextWriter.h#L24)):*
> ```objc
>     FontBase* getDefaultFont();
>     static void setDefaultFont(FontBase* font);
>     static void setupGraphics(DrawContext* constext);
> ```

typo: context
___
*[`include/gfx/seadTextWriter.h` line 25 at r2](https://reviewable.io/reviews/open-ead/sead/109#-N9aAZTu7l__A_ivgbED:-N9aAZTu7l__A_ivgbEE:bkvik16) ([raw file](https://github.com/open-ead/sead/blob/caa76dba95c6e2806af6c895ef4454101c4a2cff/include/gfx/seadTextWriter.h#L25)):*
> ```objc
>     static void setDefaultFont(FontBase* font);
>     static void setupGraphics(DrawContext* constext);
>     void getCursorFromTopLeft(Vector2f*) const;
> ```

this parameter should probably be called pos
___
*[`include/gfx/seadTextWriter.h` line 27 at r2](https://reviewable.io/reviews/open-ead/sead/109#-N9aAczl55KeQD6PXhUp:-N9aAczl55KeQD6PXhUq:b-sjwuz2) ([raw file](https://github.com/open-ead/sead/blob/caa76dba95c6e2806af6c895ef4454101c4a2cff/include/gfx/seadTextWriter.h#L27)):*
> ```objc
>     void getCursorFromTopLeft(Vector2f*) const;
>     void setCursorFromTopLeft(const Vector2f& pos);
>     void setScaleFromFontSize(const Vector2f&);
> ```

Font size?
___
*[`include/gfx/seadTextWriter.h` line 28 at r2](https://reviewable.io/reviews/open-ead/sead/109#-N9aAgoq2AhUHU0DRRXD:-N9aAgoq2AhUHU0DRRXE:bruslos) ([raw file](https://github.com/open-ead/sead/blob/caa76dba95c6e2806af6c895ef4454101c4a2cff/include/gfx/seadTextWriter.h#L28)):*
> ```objc
>     void setCursorFromTopLeft(const Vector2f& pos);
>     void setScaleFromFontSize(const Vector2f&);
>     void setScaleFromFontHeight(float scale);
> ```

Font height?
___
*[`include/gfx/seadTextWriter.h` line 30 at r2](https://reviewable.io/reviews/open-ead/sead/109#-N9aAV5W3Jv9XH-NsSeg:-N9aAV5W3Jv9XH-NsSeh:b-hl6nfr) ([raw file](https://github.com/open-ead/sead/blob/caa76dba95c6e2806af6c895ef4454101c4a2cff/include/gfx/seadTextWriter.h#L30)):*
> ```objc
>     void setScaleFromFontHeight(float scale);
>     void setProjectionAndCamera(const Projection* projection, const Camera* camera);
>     void setLineSpaceFromLineHeight(float);
> ```

the parameter is the line height

**Review by MonsterDruide1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/open-ead/sead/109)* status: all files reviewed, 4 unresolved discussions (waiting on @leoetlino)

___
*[`include/gfx/seadTextWriter.h` line 24 at r2](https://reviewable.io/reviews/open-ead/sead/109#-N9aARGEBx5C8r5Es2JY:-NAPmNrt0eNiwkpo6Nvb:b-896fix) ([raw file](https://github.com/open-ead/sead/blob/caa76dba95c6e2806af6c895ef4454101c4a2cff/include/gfx/seadTextWriter.h#L24)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

typo: context
</blockquote></details>

Done.
___
*[`include/gfx/seadTextWriter.h` line 25 at r2](https://reviewable.io/reviews/open-ead/sead/109#-N9aAZTu7l__A_ivgbED:-NAPmOg_B_VQS6Q9Pb67:b-896fix) ([raw file](https://github.com/open-ead/sead/blob/caa76dba95c6e2806af6c895ef4454101c4a2cff/include/gfx/seadTextWriter.h#L25)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

this parameter should probably be called pos
</blockquote></details>

Done.
___
*[`include/gfx/seadTextWriter.h` line 27 at r2](https://reviewable.io/reviews/open-ead/sead/109#-N9aAczl55KeQD6PXhUp:-NAPmX_o9QZcGWsrXEzY:b-896fix) ([raw file](https://github.com/open-ead/sead/blob/caa76dba95c6e2806af6c895ef4454101c4a2cff/include/gfx/seadTextWriter.h#L27)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

Font size?
</blockquote></details>

Done.
___
*[`include/gfx/seadTextWriter.h` line 28 at r2](https://reviewable.io/reviews/open-ead/sead/109#-N9aAgoq2AhUHU0DRRXD:-NAPmX8Y6VV7jw-CubC5:b-896fix) ([raw file](https://github.com/open-ead/sead/blob/caa76dba95c6e2806af6c895ef4454101c4a2cff/include/gfx/seadTextWriter.h#L28)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

Font height?
</blockquote></details>

Done.
___
*[`include/gfx/seadTextWriter.h` line 30 at r2](https://reviewable.io/reviews/open-ead/sead/109#-N9aAV5W3Jv9XH-NsSeg:-NAPmWp8Ce_UtDXgBJiL:b-896fix) ([raw file](https://github.com/open-ead/sead/blob/caa76dba95c6e2806af6c895ef4454101c4a2cff/include/gfx/seadTextWriter.h#L30)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

the parameter is the line height
</blockquote></details>

Done.

**Review by leoetlino — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/open-ead/sead/109)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @MonsterDruide1)

**Pull request merged**
