### PR TITLE
Add seadTextWriter and fix compiler warning in mathCalcCommon

### PR DESCRIPTION
**Pull request by iTNTPiston**
This change is [Reviewable](https://reviewable.io/reviews/open-ead/sead/93)

### CODE REVIEW

**Review by leoetlino — CHANGES_REQUESTED** [review]
Please run clang-format to fix the lint issues

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/open-ead/sead/93#-:-Mu5hnxc96_cCApGdsfW:b-ty2irl)* status: all files reviewed, 13 unresolved discussions (waiting on @iTNTPiston)

___
*[include/gfx/seadTextWriter.h, line 4 at r1](https://reviewable.io/reviews/open-ead/sead/93#-Mu5ibtq-3sZPyq1GJRB:-Mu5ibtq-3sZPyq1GJRC:b-n7hfot) ([raw file](https://github.com/open-ead/sead/blob/04fe4d64e895eb520dd4cd9212222a4d82c1bfd2/include/gfx/seadTextWriter.h#L4)):*
> ```objc
> 
> #include <gfx/seadColor.h>
> #include <gfx/seadDrawContext.h>
> ```

This include can be removed because DrawContext can be forward declared.
___
*[include/gfx/seadTextWriter.h, line 18 at r1](https://reviewable.io/reviews/open-ead/sead/93#-Mu5hqnX1MIWWO45RZ43:-Mu5hqnX1MIWWO45RZ44:b3hzr2m) ([raw file](https://github.com/open-ead/sead/blob/04fe4d64e895eb520dd4cd9212222a4d82c1bfd2/include/gfx/seadTextWriter.h#L18)):*
> ```objc
>             virtual ~TextWriter();
> 
>             void printImpl_(char const*, int, bool, sead::BoundBox2<float>*);
> ```

`sead::BoundBox2<float>` should be `BoundBox2f` (no need to qualify the name since you're already in the sead namespace), and `char const*` should be `const char*`
___
*[include/gfx/seadTextWriter.h, line 19 at r1](https://reviewable.io/reviews/open-ead/sead/93#-Mu5i--lEJwhDfztSJQN:-Mu5i--lEJwhDfztSJQO:b5hxejp) ([raw file](https://github.com/open-ead/sead/blob/04fe4d64e895eb520dd4cd9212222a4d82c1bfd2/include/gfx/seadTextWriter.h#L19)):*
> ```objc
> 
>             void printImpl_(char const*, int, bool, sead::BoundBox2<float>*);
>             void printf(char const*, ...);
> ```

`const char* format`
___
*[include/gfx/seadTextWriter.h, line 20 at r1](https://reviewable.io/reviews/open-ead/sead/93#-Mu5i1jVDYnwtC-mJstP:-Mu5i1jVDYnwtC-mJstQ:b-7ropln) ([raw file](https://github.com/open-ead/sead/blob/04fe4d64e895eb520dd4cd9212222a4d82c1bfd2/include/gfx/seadTextWriter.h#L20)):*
> ```objc
>             void printImpl_(char const*, int, bool, sead::BoundBox2<float>*);
>             void printf(char const*, ...);
>             void printf(char16_t const*, ...);
> ```

ditto
___
*[include/gfx/seadTextWriter.h, line 21 at r1](https://reviewable.io/reviews/open-ead/sead/93#-Mu5i2Pf53QOxIaob51t:-Mu5i2Pf53QOxIaob51u:bzfrv9x) ([raw file](https://github.com/open-ead/sead/blob/04fe4d64e895eb520dd4cd9212222a4d82c1bfd2/include/gfx/seadTextWriter.h#L21)):*
> ```objc
>             void printf(char const*, ...);
>             void printf(char16_t const*, ...);
>             void setScaleFromFontHeight(float);
> ```

`float scale`
___
*[include/gfx/seadTextWriter.h, line 23 at r1](https://reviewable.io/reviews/open-ead/sead/93#-Mu5i3Pi2ud4zg49q231:-Mu5i3Pj6NBxlhdDq4Ci:bkfed1z) ([raw file](https://github.com/open-ead/sead/blob/04fe4d64e895eb520dd4cd9212222a4d82c1bfd2/include/gfx/seadTextWriter.h#L23)):*
> ```objc
>             void setScaleFromFontHeight(float);
>             void beginDraw();
>             static void setupGraphics(sead::DrawContext*);
> ```

`DrawContext* context`
___
*[include/gfx/seadTextWriter.h, line 25 at r1](https://reviewable.io/reviews/open-ead/sead/93#-Mu5iTNWEKlHxCm_LVv3:-Mu5iTNWEKlHxCm_LVv4:b-74fgw1) ([raw file](https://github.com/open-ead/sead/blob/04fe4d64e895eb520dd4cd9212222a4d82c1bfd2/include/gfx/seadTextWriter.h#L25)):*
> ```objc
>             static void setupGraphics(sead::DrawContext*);
> 
>             sead::Viewport *mViewport;
> ```

Viewport*
___
*[include/gfx/seadTextWriter.h, line 26 at r1](https://reviewable.io/reviews/open-ead/sead/93#-Mu5iTys7uGEA3ZbxCTt:-Mu5iTys7uGEA3ZbxCTu:b-7n185m) ([raw file](https://github.com/open-ead/sead/blob/04fe4d64e895eb520dd4cd9212222a4d82c1bfd2/include/gfx/seadTextWriter.h#L26)):*
> ```objc
> 
>             sead::Viewport *mViewport;
>             sead::Projection *mProjection;
> ```

Projection*
___
*[include/gfx/seadTextWriter.h, line 27 at r1](https://reviewable.io/reviews/open-ead/sead/93#-Mu5iUmNBwtszQYfr2qT:-Mu5iUmNBwtszQYfr2qU:b14edpc) ([raw file](https://github.com/open-ead/sead/blob/04fe4d64e895eb520dd4cd9212222a4d82c1bfd2/include/gfx/seadTextWriter.h#L27)):*
> ```objc
>             sead::Viewport *mViewport;
>             sead::Projection *mProjection;
>             sead::Camera *mCamera;
> ```

Camera*
___
*[include/gfx/seadTextWriter.h, line 28 at r1](https://reviewable.io/reviews/open-ead/sead/93#-Mu5i6XZAKrCctd1IjI-:-Mu5i6XZAKrCctd1IjI0:bk5437c) ([raw file](https://github.com/open-ead/sead/blob/04fe4d64e895eb520dd4cd9212222a4d82c1bfd2/include/gfx/seadTextWriter.h#L28)):*
> ```objc
>             sead::Projection *mProjection;
>             sead::Camera *mCamera;
>             int TextWriter_x20;
> ```

We use a different naming convention for placeholder field names: TextWriter_xNN -> _nn (so this should be _20)
___
*[include/gfx/seadTextWriter.h, line 31 at r1](https://reviewable.io/reviews/open-ead/sead/93#-Mu5iHxIEddX1GoYMeDm:-Mu5iHxIEddX1GoYMeDn:b2nhw4r) ([raw file](https://github.com/open-ead/sead/blob/04fe4d64e895eb520dd4cd9212222a4d82c1bfd2/include/gfx/seadTextWriter.h#L31)):*
> ```objc
>             int TextWriter_x24;
>             int TextWriter_x28;
>             int TextWriter_x2C;
> ```

_2c
___
*[include/gfx/seadTextWriter.h, line 32 at r1](https://reviewable.io/reviews/open-ead/sead/93#-Mu5iJGCD3tC9zpZmZgH:-Mu5iJGCD3tC9zpZmZgI:b-5n8rx6) ([raw file](https://github.com/open-ead/sead/blob/04fe4d64e895eb520dd4cd9212222a4d82c1bfd2/include/gfx/seadTextWriter.h#L32)):*
> ```objc
>             int TextWriter_x28;
>             int TextWriter_x2C;
>             sead::Vector2<float> mScale;
> ```

`Vector2f` (no need for `sead::`)
___
*[include/gfx/seadTextWriter.h, line 36 at r1](https://reviewable.io/reviews/open-ead/sead/93#-Mu5iXHu9rFoM6I5c7A8:-Mu5iXHu9rFoM6I5c7A9:b-vf5ndo) ([raw file](https://github.com/open-ead/sead/blob/04fe4d64e895eb520dd4cd9212222a4d82c1bfd2/include/gfx/seadTextWriter.h#L36)):*
> ```objc
>             int TextWriter_x48;
>             float mLineSpace;
>             sead::BoundBox2<float> *mBoundBox2;
> ```

BoundBox2f*

**Review by leoetlino — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/open-ead/sead/93)* status: all files reviewed, 13 unresolved discussions (waiting on @iTNTPiston)

**Review by iTNTPiston — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/open-ead/sead/93)* status: 1 of 2 files reviewed, 13 unresolved discussions (waiting on @leoetlino)

___
*[include/gfx/seadTextWriter.h, line 4 at r1](https://reviewable.io/reviews/open-ead/sead/93#-Mu5ibtq-3sZPyq1GJRB:-Mu74UtN6KSQw7GRNFFF:b-896fix) ([raw file](https://github.com/open-ead/sead/blob/04fe4d64e895eb520dd4cd9212222a4d82c1bfd2/include/gfx/seadTextWriter.h#L4)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

This include can be removed because DrawContext can be forward declared.
</blockquote></details>

Done.
___
*[include/gfx/seadTextWriter.h, line 18 at r1](https://reviewable.io/reviews/open-ead/sead/93#-Mu5hqnX1MIWWO45RZ43:-Mu74VgiCD6dStuxDtYF:b-896fix) ([raw file](https://github.com/open-ead/sead/blob/04fe4d64e895eb520dd4cd9212222a4d82c1bfd2/include/gfx/seadTextWriter.h#L18)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

`sead::BoundBox2<float>` should be `BoundBox2f` (no need to qualify the name since you're already in the sead namespace), and `char const*` should be `const char*`
</blockquote></details>

Done.
___
*[include/gfx/seadTextWriter.h, line 19 at r1](https://reviewable.io/reviews/open-ead/sead/93#-Mu5i--lEJwhDfztSJQN:-Mu74Vty3K_0UAvRJYK2:b-896fix) ([raw file](https://github.com/open-ead/sead/blob/04fe4d64e895eb520dd4cd9212222a4d82c1bfd2/include/gfx/seadTextWriter.h#L19)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

`const char* format`
</blockquote></details>

Done.
___
*[include/gfx/seadTextWriter.h, line 20 at r1](https://reviewable.io/reviews/open-ead/sead/93#-Mu5i1jVDYnwtC-mJstP:-Mu74W9qA098MMAb3_Rd:b-896fix) ([raw file](https://github.com/open-ead/sead/blob/04fe4d64e895eb520dd4cd9212222a4d82c1bfd2/include/gfx/seadTextWriter.h#L20)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[include/gfx/seadTextWriter.h, line 21 at r1](https://reviewable.io/reviews/open-ead/sead/93#-Mu5i2Pf53QOxIaob51t:-Mu74WMB8AMC6NOK1x7S:b-896fix) ([raw file](https://github.com/open-ead/sead/blob/04fe4d64e895eb520dd4cd9212222a4d82c1bfd2/include/gfx/seadTextWriter.h#L21)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

`float scale`
</blockquote></details>

Done.
___
*[include/gfx/seadTextWriter.h, line 23 at r1](https://reviewable.io/reviews/open-ead/sead/93#-Mu5i3Pi2ud4zg49q231:-Mu74X0o3n3zbf2hAZvh:b-896fix) ([raw file](https://github.com/open-ead/sead/blob/04fe4d64e895eb520dd4cd9212222a4d82c1bfd2/include/gfx/seadTextWriter.h#L23)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

`DrawContext* context`
</blockquote></details>

Done.
___
*[include/gfx/seadTextWriter.h, line 25 at r1](https://reviewable.io/reviews/open-ead/sead/93#-Mu5iTNWEKlHxCm_LVv3:-Mu74XAc8DoSdTpIIt4V:b-896fix) ([raw file](https://github.com/open-ead/sead/blob/04fe4d64e895eb520dd4cd9212222a4d82c1bfd2/include/gfx/seadTextWriter.h#L25)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

Viewport*
</blockquote></details>

Done.
___
*[include/gfx/seadTextWriter.h, line 26 at r1](https://reviewable.io/reviews/open-ead/sead/93#-Mu5iTys7uGEA3ZbxCTt:-Mu74XReAFgkF1OWIlg8:b-896fix) ([raw file](https://github.com/open-ead/sead/blob/04fe4d64e895eb520dd4cd9212222a4d82c1bfd2/include/gfx/seadTextWriter.h#L26)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

Projection*
</blockquote></details>

Done.
___
*[include/gfx/seadTextWriter.h, line 27 at r1](https://reviewable.io/reviews/open-ead/sead/93#-Mu5iUmNBwtszQYfr2qT:-Mu74Xbi4-s59DHQhaq5:b-896fix) ([raw file](https://github.com/open-ead/sead/blob/04fe4d64e895eb520dd4cd9212222a4d82c1bfd2/include/gfx/seadTextWriter.h#L27)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

Camera*
</blockquote></details>

Done.
___
*[include/gfx/seadTextWriter.h, line 28 at r1](https://reviewable.io/reviews/open-ead/sead/93#-Mu5i6XZAKrCctd1IjI-:-Mu74XwH6EC6oO8cozTY:b-896fix) ([raw file](https://github.com/open-ead/sead/blob/04fe4d64e895eb520dd4cd9212222a4d82c1bfd2/include/gfx/seadTextWriter.h#L28)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

We use a different naming convention for placeholder field names: TextWriter_xNN -> _nn (so this should be _20)
</blockquote></details>

Done.
___
*[include/gfx/seadTextWriter.h, line 31 at r1](https://reviewable.io/reviews/open-ead/sead/93#-Mu5iHxIEddX1GoYMeDm:-Mu74Y696Pm297ZeLcD2:b-896fix) ([raw file](https://github.com/open-ead/sead/blob/04fe4d64e895eb520dd4cd9212222a4d82c1bfd2/include/gfx/seadTextWriter.h#L31)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

_2c
</blockquote></details>

Done.
___
*[include/gfx/seadTextWriter.h, line 32 at r1](https://reviewable.io/reviews/open-ead/sead/93#-Mu5iJGCD3tC9zpZmZgH:-Mu74YP91P-qlKuS-AP3:b-896fix) ([raw file](https://github.com/open-ead/sead/blob/04fe4d64e895eb520dd4cd9212222a4d82c1bfd2/include/gfx/seadTextWriter.h#L32)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

`Vector2f` (no need for `sead::`)
</blockquote></details>

Done.
___
*[include/gfx/seadTextWriter.h, line 36 at r1](https://reviewable.io/reviews/open-ead/sead/93#-Mu5iXHu9rFoM6I5c7A8:-Mu74YZ92M9oER73ShHa:b-896fix) ([raw file](https://github.com/open-ead/sead/blob/04fe4d64e895eb520dd4cd9212222a4d82c1bfd2/include/gfx/seadTextWriter.h#L36)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

BoundBox2f*
</blockquote></details>

Done.

**Review by leoetlino — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/open-ead/sead/93)* status: all files reviewed, 1 unresolved discussion (waiting on @iTNTPiston)

___
*[include/gfx/seadTextWriter.h, line 44 at r3](https://reviewable.io/reviews/open-ead/sead/93#-Mu74atrEK9GcZOH6SjH:-Mu74atrEK9GcZOH6SjI:btp819i) ([raw file](https://github.com/open-ead/sead/blob/9637df84664939182ad79f9cfc3db48b4d05d675/include/gfx/seadTextWriter.h#L44)):*
> ```objc
>     DrawContext* mDrawContext;
> };
> };  // namespace sead
> ```

nit: no need for `;` to close a namespace

**Review by leoetlino — APPROVED** [review]
:lgtm: Thanks for the PR!

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/open-ead/sead/93#-:-Mu75a7RDBg4-7bQg-2L:bke5l8x)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @iTNTPiston)

**Pull request merged**
