### PR TITLE
Move `GameFrameworkNx` and `DebugFontMgrNvn` for correct file layout

### PR DESCRIPTION
**Pull request by MonsterDruide1**
Moving around some of the files according to some messages in the Discord-Server:
https://discord.com/channels/688807550715560050/794951602396987432/1115848275581485107

(not directly quoted, but adjusted/corrected according to later messages)
> DebugFontMgrJis1Nvn has it's own file instead of being tied to seadFontMgr
> so it would be `gfx/nvn/seadDebugFontMgrNvn.cpp`

> also `seadGameFrameworkNx` should be in `framework/nx` instead of just `framework`

- - -
This change is [Reviewable](https://reviewable.io/reviews/open-ead/sead/131)

### CODE REVIEW

**Comment by MonsterDruide1** [comment]
Might close #128 ?

**Review by break-core — COMMENTED** [review]
Looks good! Also, for *skeptical* maintainers, these file paths were sourced from MK8DX:
`D:/home/Project/TurboS/App/Lib/sead/library/modules/src/framework/nx/seadGameFrameworkNx.cpp`
`D:/home/Project/TurboS/App/Lib/sead/library/modules/src/gfx/nvn/seadDebugFontMgrNvn.cpp`

> *[Reviewable](https://reviewable.io/reviews/open-ead/sead/131#-:-NcTR0er7SdUbf6ZrN0g:bl8udpy)* status: 0 of 6 files reviewed, all discussions resolved

**Comment by MonsterDruide1** [comment]
@break-core Does this fully cover the second point you described in the issue? I was confused by your sentence about merging stuff...

**Comment by break-core** [comment]
@MonsterDruide1 Yes, this should fully cover that. Everything looks to be correct, sorry about any confusion.

**Pull request merged**
